# Generated by Django 5.0.2 on 2024-03-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
