# Generated by Django 5.0.2 on 2024-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
