# Generated by Django 5.0.2 on 2024-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_description_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Превью'),
        ),
    ]
